// <auto-generated />
using System;
using IncomeExpense_WPF.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace IncomeExpense_WPF.Migrations
{
    [DbContext(typeof(IncomeExpenseDbContext))]
    partial class IncomeExpenseDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("IncomeExpense_WPF.Model.IncomeExpense", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ExpenseName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("ExpenseSum")
                        .HasColumnType("float");

                    b.Property<double?>("ExpenseSumTotalEveryTwoWeeks")
                        .HasColumnType("float");

                    b.Property<double?>("IncomeEveryTwoWeeks")
                        .HasColumnType("float");

                    b.Property<bool?>("IsMonthlyPayment")
                        .HasColumnType("bit");

                    b.Property<DateTime>("RegistrationDay")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<double?>("TotalSaved")
                        .HasColumnType("float");

                    b.Property<double?>("TotalSavedMonth")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("incomeExpense");
                });
#pragma warning restore 612, 618
        }
    }
}
